<script>
	import { Button, Checkbox } from "fluent-svelte";
</script>

<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>

<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>
<Button>Click me!</Button>
<Checkbox>Check me!</Checkbox>